# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:31:31+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field

from . import Record


class FieldFormatGetResponse(BaseModel):
    page: Optional[int] = Field(None, description='Current page.', examples=[1])
    per_page: Optional[int] = Field(
        None,
        description='Requested amount of records shown per page of results.',
        examples=[5],
    )
    records: Optional[List[Record]] = None
    request_url: Optional[str] = Field(
        None,
        description='The URL of current page of results.',
        examples=[
            'https://api.digitalnz.org/records/35806021/more_like_this.json?mlt_fields=title,description&page=1&fields=title,description,subject,display_collection,category&and[category]=Images'
        ],
    )
    result_count: Optional[int] = Field(
        None, description='Total number of matching search results.', examples=[1907]
    )


class FieldFormatGetResponseModel(BaseModel):
    pass
