# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:31:31+00:00

from __future__ import annotations

from pydantic import BaseModel


class FieldFormatGetResponse(BaseModel):
    pass
